### ISSUE TITLE
画像読み込み中のloading画像を動くようにしたい

### ISSUE THREAD

**Issue by kiiiichan** [kiiiichan/typing_game#12]

**Comment by kiiiichan** [comment]
https://coco-factory.jp/ugokuweb/move01-cat/loading/

**Comment by hash52** [comment]
単にくるくるしたいだけであればローディング画像をgifにするといけそうです
「何%読み込み済み」まで詳細に表示させたいのであれば、ライブラリ探しましょう

**Comment by hash52** [comment]
例

https://loading.io/progress/

※とりあえず"loading bar js library"でググった一番上に出てきたやつですので、ベストプラクティスかどうかは微妙です

**Comment by kiiiichan** [comment]
特定のタイミングでJSから画像サイズを変更するやり方　
https://www.nishishi.com/javascript-tips/image-resize-width-height.html

※HTMLでの縦横サイズ指定よりも、CSSでの縦横サイズ指定の方が優先されるため、CSSで画像サイズが指定されている状況では、JavaScriptでwidthプロパティやheightプロパティを変更しても表示に反映されません。
その際は、widthプロパティやheightプロパティではなく、スタイルシート側の指定であるstyle.widthプロパティやstyle.heightプロパティに値を代入しましょう。

**Comment by kiiiichan** [comment]
画像の中央寄せ（上下中央はちょっとめんどくさい）
https://webdesignday.jp/inspiration/technique/css/4175/#align-items
