### ISSUE TITLE
issueの練習

### ISSUE THREAD

**Issue by kiiiichan** [kiiiichan/typing_game#2]
練習コメント
```
aaa
```
マークダウン記法が使えます。➡マークダウン　チートシート

**Comment by hash52** [comment]
https://qiita.com/kamorits/items/6f342da395ad57468ae3

**Comment by kiiiichan** [comment]
コミットメッセージ　issue　閉じる　で git にコミットするタイミングで　#2　と残しておくとよい

**Comment by hash52** [comment]
やり直しです
再度コミットしてissueを閉じて置いてください
